// This file has been generated by Specta. DO NOT EDIT.

export type GenericType<A> = { my_field: string; generic: A }

export type MyEither<L, R> = { Left: L } | { Right: R }

export type MyEnum = "A" | "B" | "C"

export type TypeOne = { a: string; b: GenericType<number>; cccccc: MyEnum }

